;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Ability.Evade",DevComment="")
+GameplayTagList=(Tag="Ability.FindCover",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="Damage value for SetByCaller")
+GameplayTagList=(Tag="Event",DevComment="")
+GameplayTagList=(Tag="Event.Ability",DevComment="")
+GameplayTagList=(Tag="Event.Ability.End",DevComment="")
+GameplayTagList=(Tag="Event.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Attack.FireBullet",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Death",DevComment="")
+GameplayTagList=(Tag="Spawn.Enemy",DevComment="")
+GameplayTagList=(Tag="Spawn.Enemy.Wave1",DevComment="")
+GameplayTagList=(Tag="Spawn.Enemy.Wave2",DevComment="")
+GameplayTagList=(Tag="Spawn.Enemy.Wave3",DevComment="")
+GameplayTagList=(Tag="Status.BlockOneHit",DevComment="For ShieldItem")
+GameplayTagList=(Tag="Status.Death.Dead",DevComment="Dead State")

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Spawn", Comment="스폰의 루트 태그입니다.")
GameplayTagList=(Tag="Spawn.Enemy", Comment="적 스폰 태그입니다.")
GameplayTagList=(Tag="Spawn.Enemy.Melee", Comment="근접 공격 적 스폰 태그입니다.")
GameplayTagList=(Tag="Spawn.Enemy.Ranged", Comment="원거리 공격 적 스폰 태그입니다.")
GameplayTagList=(Tag="Spawn.Enemy.Boss", Comment="보스 스폰 태그입니다.")
GameplayTagList=(Tag="Spawn.Pickup", Comment="픽업 아이템 스폰 태그입니다.")

